name: pure_scents
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  url_launcher: ^6.3.1
  http: ^1.2.1
  intl: ^0.19.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assests/Screenshot 2026-06-08 125015.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "lib/assests/Screenshot 2026-06-08 125015.png"
  android_12:
    image: "lib/assests/Screenshot 2026-06-08 125015.png"
    color: "#ffffff"
  web: false

flutter:
  uses-material-design: true
  assets:
    - lib/assests/
